-- INDEX - IN SQL IS LIKE A SHORTCUT THAT MAKES SEARCHING DATA IN A TABLE FASTER. IT IS THREE TYPES
-- CLUSTERED INDEX - SORTS AND STORE ROWS PHYSICALLY IN ORDER (ONLY ONE PER TABLE).
-- NON-CLUSTERED INDEX - CREATE A SEPARATE STRUCTURE POINTING TO THE DATA (CAN HAVE MANY PER TABLE)
-- UNIQUE INDEX - ENSURES ALL VALUES IN A COLUMN ARE UNIQUE

create index indx_nmployees_name
on employees(emp_name);
select * from employees where emp_name="Neha sharma"