CREATE TABLE employee(
	employee_id SERIAL PRIMARY KEY,
	nam VARCHAR(100) NOT NULL,
	position VARCHAR(50),
	department VARCHAR(50),
	hire_date DATE,
	salary NUMERIC(10,2)
);
SELECT * FROM employee;
--ADD A NEW COLUMN IN TABLE WITH AGE NAME AND SET THE VALUE
	UPDATE employee
	SET age=18
	WHERE AGE IS NULL ;
--ALTER COLUMN AND DATATYPE IN SQL
	--TO RENAME THE NAME COLUMN TO FULL-NAME
	ALTER TABLE employee
	rename column name to full_name;
	--TO CHANGE THE AGE COLUMN'S DATA TYPE FROM INT TO SMALEST
	ALTER TABLE employee
	ALTER COLUMN age  TYPE SMALLINT;
	
	--TO ADDING CHECK CONSTRAINT TO AGE COLUMN
	ALTER TABLE employee
	ADD CONSTRAINT AGE CHECK(age >18);